# Rename this file to languages.toml to enable multilingual support
[zh-cn]
contentDir = "content/zh-cn"
languageName = "简体中文"
languagedirection = "ltr"
title = "My Shares and Proofs"
weight = 1

[en]
contentDir = "content/en"
languageName = "English"
languagedirection = "ltr"
title = "My Shares and Proofs"
weight = 2
