# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2024
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "💫"
subtitle = "Freelance Researcher & Developer."

[sidebar.avatar]
enabled = true
local = true
src = "img/pika.jpg"

[article]
headingAnchor = true
math = true
readingTime = false

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[colorScheme]
toggle = true
default = "auto"

## Widgets
### Homepage Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"
[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"
[widgets.homepage.params]
limit = 10

### Page Widgets
[[widgets.page]]
type = "toc"

## Open Graph
[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

## Image Processing
[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true



## Comments
[comments]
enabled = true
provider = "giscus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = "iamhyc/iamhyc.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkxMTEzMDI0Mjk="
category = "Announcements"
categoryID = "DIC_kwDOBqJXHc4CiEQu"
mapping = "pathname"
lightTheme = "noborder_light"
darkTheme = "noborder_dark"
reactionsEnabled = 1
emitMetadata = 1

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
